CREATE TABLE SystemEvents (
  ID INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  CustomerID bigint NULL,
  ReceivedAt DATETIME NULL,
  DeviceReportedTime DATETIME NULL,
  Facility SMALLINT NULL,
  Priority SMALLINT NULL,
  FromHost VARCHAR(60) NULL,
  Message TEXT,
  NTSeverity INT NULL,
  Importance INT NULL,
  EventSource VARCHAR(60),
  EventUser VARCHAR(60),
  EventCategory INT NULL,
  EventID INT NULL,
  EventBinaryData TEXT,
  MaxAvailable INT NULL,
  CurrUsage INT NULL,
  MinUsage INT NULL,
  MaxUsage INT NULL,
  InfoUnitID INT NULL,
  SysLogTag VARCHAR(60),
  EventLogType VARCHAR(60),
  GenericFileName VARCHAR(60),
  SystemID INT NULL,
  PRIMARY KEY (ID)
);